# build only master branch on commit's
# all other branches build on PullRequest creation
branches:
  only:
    - master

language: rust

rust:
# build nightly only for the time beeing
  - nightly

matrix:
  fast_finish: true
  include:
    - name: "build 64Bit"
      install:
        - sudo apt-get install gcc-aarch64-linux-gnu
        - cargo install cargo-xbuild
        - cargo install cargo-make 
        - rustup target add aarch64-unknown-linux-gnu
        - rustup component add rust-src
        - rustup component add llvm-tools-preview
        # remove local path in the dependencies of the cargo file to ensure we use the version from crates.io
        - sed -i 's/path.*=.*"\.\{2\}.*", version/version/g' Cargo.toml
      script: cargo make --profile a64-travis pi3

    - name: "build 32Bit"
      install:
        - sudo apt-get install gcc-arm-linux-gnueabihf
        - cargo install cargo-xbuild
        - cargo install cargo-make 
        - rustup target add armv7-unknown-linux-gnueabihf
        - rustup component add rust-src
        - rustup component add llvm-tools-preview
        - sed -i 's/path.*=.*"\.\{2\}.*", version/version/g' Cargo.toml
      # remove local path in the dependencies of the cargo file to ensure we use the version from crates.io
      script: cargo make --profile a32 pi3

    - name: "unit tests"
      install:
        # remove local path in the dependencies of the cargo file to ensure we use the version from crates.io
        - sed -i 's/path.*=.*"\.\{2\}.*", version/version/g' Cargo.toml
      script: cargo test --tests --features ruspiro_pi3

    - name: "doc tests"
      install:
        # remove local path in the dependencies of the cargo file to ensure we use the version from crates.io
        - sed -i 's/path.*=.*"\.\{2\}.*", version/version/g' Cargo.toml
      script: cargo test --doc --features ruspiro_pi3
