[package]
name = "ruspiro-interrupt"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.0.1" # remember to update html_root_url
description = "This crates provides features to implement interrupt handler for common Raspberry Pi interrupts."
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-interrupt/tree/v0.0.1"
documentation = "https://docs.rs/ruspiro-interrupt/0.0.1"
readme = "README.md"
keywords = ["RusPiRo", "baremetal", "raspberrypi", "interrupt"]
categories = ["no-std", "embedded"]
edition = "2018"

[workspace]
members = ["macros"]

[lib]

[dependencies]
ruspiro-register = "0.0.2"
ruspiro-interrupt-macros = { path = "./macros" }
lazy_static = { version = "1.3.0", features = ["spin_no_std"] }

[features]