[package]
name = "ruspiro-interrupt"
authors = ["Andre Borrmann <pspwizard@gmx.de>"]
version = "0.3.0" # remember to update html_root_url
description = "Providing a simple and convinient way to implement interrupt handler for Raspberry Pi interrupts."
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-interrupt/"
documentation = "https://docs.rs/ruspiro-interrupt/0.3.0"
readme = "README.md"
keywords = ["RusPiRo", "baremetal", "raspberrypi", "interrupt"]
categories = ["no-std", "embedded"]
edition = "2018"

[badges]
travis-ci = { repository = "RusPiRo/ruspiro-interrupt", branch = "master" }
maintenance = { status = "actively-developed" }

[lib]

[dependencies]
paste = "0.1.5"
ruspiro-register = { path = "../register", version = "0.3" }
ruspiro-interrupt-core = { path = "./core", version = "0.2" }
ruspiro-interrupt-macros = { path = "./macros", version = "0.2" }
ruspiro-singleton = { path = "../singleton", version = "0.3" }

[features]
default = ["ruspiro_pi3"]
ruspiro_pi3 = []
