[package]
name = "ruspiro-interrupt"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.1.0" # remember to update html_root_url
description = "This crates provides features to implement interrupt handler for common Raspberry Pi interrupts."
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-interrupt/tree/v0.1.0"
documentation = "https://docs.rs/ruspiro-interrupt/0.1.0"
readme = "README.md"
keywords = ["RusPiRo", "baremetal", "raspberrypi", "interrupt"]
categories = ["no-std", "embedded"]
edition = "2018"

[workspace]
members = ["macros"]

[lib]

[dependencies]
ruspiro-register = "0.1.1"
ruspiro-interrupt-macros = { path = "./macros", version = "0.1.0" }
ruspiro-singleton = "0.1.0"

[features]
default = ["ruspiro_pi3"]
ruspiro_pi3 = []