#***********************************************************************************************************************
# cargo make tasks to build the example for the Raspberry Pi
#***********************************************************************************************************************

# AARCH64 specific profile environment varialbles
[env.development]
CC = "aarch64-none-elf-gcc"
AR = "aarch64-none-elf-ar"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53 -C link-arg=-nostartfiles -C link-arg=-T./link64.ld"

# AARCH64 specific Pipeline env. variables. "aarch64-none-elf" is not available there as it seems
[env.pipeline]
CC = "aarch64-linux-gnu-gcc"
AR = "aarch64-linux-gnu-ar"
CFLAGS = "-march=armv8-a -Wall -O3 -nostdlib -nostartfiles -ffreestanding -mtune=cortex-a53"
RUSTFLAGS = "-C linker=${CC} -C target-cpu=cortex-a53 -C link-arg=-nostartfiles -C link-arg=-T./link64.ld"

[tasks.build]
command = "cargo"
args = ["build", "--release", "--features", "${FEATURES}"]

[tasks.clippy]
env = { FEATURES = "pi3, async" }
command = "cargo"
args = ["clippy", "--features", "${FEATURES}"]

[tasks.doc]
env = { FEATURES = "pi3, async" }
command = "cargo"
args = ["doc", "--features", "${FEATURES}", "--open"]

[tasks.pi3_blocking]
env = { FEATURES = "pi3" }
run_task = "build"

[tasks.pi3_async]
env = { FEATURES = "pi3, async" }
run_task = "build"

[tasks.pi3]
dependencies = ["pi3_blocking", "pi3_async"]

[tasks.pi4_low_blocking]
env = { FEATURES = "pi4_low" }
run_task = "build"

[tasks.pi4_low_async]
env = { FEATURES = "pi4_low, async" }
run_task = "build"

[tasks.pi4_high_blocking]
env = { FEATURES = "pi4_low" }
run_task = "build"

[tasks.pi4_high_async]
env = { FEATURES = "pi4_low, async" }
run_task = "build"

[tasks.pi4_low]
dependencies = ["pi4_low_blocking", "pi4_low_async"]

[tasks.pi4_high]
dependencies = ["pi4_high_blocking", "pi4_high_async"]

[tasks.all]
dependencies = ["pi3_blocking", "pi3_async", "pi4_high_blocking", "pi4_high_async"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.publish_dry]
env = { FEATURES = "pi3, async" }
command = "cargo"
args = ["publish", "--dry-run", "--features", "${FEATURES}", "--allow-dirty"]

[tasks.publish]
env = { FEATURES = "pi3, async" }
command = "cargo"
args = ["publish", "--token", "${CRATES_TOKEN}", "--allow-dirty", "--features", "${FEATURES}"]
